backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre de la page", name: "title", widget: "string" }
      - { label: "Nom dans le menu", name: "sidebar_label", widget: "string" }
      - { label: "Position dans le menu", name: "sidebar_position", widget: "number", default: 10 }
      - { label: "Description (optionnel)", name: "description", widget: "string", required: false }
      - { label: "Corps du document", name: "body", widget: "markdown" }
