backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

site_url: https://stirring-gumption-20f3cf.netlify.app